### get 
GET http://localhost:3001/api/products HTTP/1.1

### get by id
GET http://localhost:3001/api/products/641796126f2bf4cedb59e353 HTTP/1.1

### post 
POST http://localhost:3001/api/products HTTP/1.1
content-type: application/json

{
    "category": "appliances",
    "sub_category": "frigde",
    "brand": "samsung",
    "model": "RT38K5932S 323L",
    "price": 230000,
    "stock": 20,
    "properties": {
      "origin_country": "argentina",
      "light": "led",
      "color": "black"
    }
}

### DELETE
DELETE http://localhost:3001/api/products/6417b09e4e6447e66f3b719f

### update
PUT http://localhost:3001/api/products/6417b09e4e6447e66f3b719f HTTP/1.1
content-type: application/json

{
    "category": "appliances",
    "sub_category": "frigde",
    "brand": "samung",
    "model": "RT38K5932S 323L",
    "price": 230000,
    "stock": 20,
    "properties": {
      "origin_country": "argentina",
      "light": "led",
      "color": "black"
    }
}